First major implementation
companieshouse/logging-stack pull request #1
Opened 2021-02-03 14:09 UTC by Jata2k

Resolves: DVOP-1603

2021-03-11 10:57 UTC, DrewHarvard commented on groups/bootstrap/locals.tf
> +  path = "team-${var.team}/${var.account_name}/${var.region}/${var.repository_name}"
You'll have to add `${var.environment}` to this path

2021-03-11 10:57 UTC, DrewHarvard commented on groups/logging/locals.tf
> +  path = "team-${var.team}/${var.account_name}/${var.region}/${var.repository_name}"
You'll have to add `${var.environment}` to this path

2021-03-11 10:58 UTC, DrewHarvard commented on groups/shared/locals.tf
> +  path = "team-${var.team}/${var.account_name}/${var.region}/${var.repository_name}"
You'll have to add `${var.environment}` to this path

2021-03-18 08:01 UTC, marcransome requested changes

2021-03-25 12:10 UTC, Jata2k commented on groups/bootstrap/cloud-init.tf
> +      instance_hostname = "${var.service}-${var.environment}-bootstrap.${local.dns_zone_name}"
Good point. I'll introduce this into a subsequent PR I think as I'll be rebuilding the stack once more in development anyway. That's probably as good a time as any to add this change

2021-03-29 09:42 UTC, marcransome approved these changes

2021-03-29 10:03 UTC, marcransome submitted a review, later dismissed

2021-03-29 12:05 UTC, merged